# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  #
# Commands and Apps to be executed at launch

# Random wallpaper per monitor every hour
exec-once = ~/.config/hypr/UserScripts/WallpaperPerMonitor.sh

